# Funding options for MIESC
# These are supported funding platforms

github: fboiero
# ko_fi: # Replace with your Ko-fi username
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# custom: ["https://www.paypal.me/fboiero"]
