// Auto-generated Certora specification for MyContract
// Generated by MIESC v5.1.2 from 3 findings
// Review and adapt before running `certoraRun`

methods {
    // TODO: add function signatures from your contract
}

// (1/3) No reentrancy: function does not re-enter itself via external call
// Confidence: 75%
// @dev Ensures withdraw/transfer is not reentered
rule noReentrancy_withdraw(env e, address user) {
    require balances[user] > 0;
    uint256 balanceBefore = nativeBalances[currentContract];
    withdraw(e, user);
    assert nativeBalances[currentContract] == balanceBefore - balances[user],
        "Reentrancy detected: balance decreased more than expected";
}

// (2/3) No reentrancy: function does not re-enter itself via external call
// Confidence: 75%
// @dev Ensures withdraw/transfer is not reentered
rule noReentrancy_reentrancy(env e, address user) {
    require balances[user] > 0;
    uint256 balanceBefore = nativeBalances[currentContract];
    reentrancy(e, user);
    assert nativeBalances[currentContract] == balanceBefore - balances[user],
        "Reentrancy detected: balance decreased more than expected";
}

// (3/3) Return value of external calls must be checked
// Confidence: 75%
// @dev targetFunction must handle failed external calls
rule checkedReturn_targetFunction(env e) {
    bool callResult;
    uint256 stateBefore = contractState();
    callResult = targetFunction(e);
    uint256 stateAfter = contractState();
    assert callResult || stateBefore == stateAfter,
        "State changed despite failed call";
}
