"""
Formal Verification Runner
===========================

Executes the specs generated by `spec_generator.py` against real verifiers:
  - Certora Prover (via certoraRun CLI)
  - Halmos (symbolic testing in Foundry)
  - SMTChecker (via solc --model-checker-engine)
  - Scribble (ConsenSys annotation instrumentation + assertion check)
  - Kontrol (KEVM/Foundry symbolic invariant proving)

This closes the loop: MIESC finds → generates spec → actually runs the proof.

Author: Fernando Boiero <fboiero@frvm.utn.edu.ar>
License: AGPL-3.0
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class VerificationResult:
    """Result of running a formal verification spec."""

    tool: str  # "certora", "halmos", "smtchecker", "scribble", "kontrol"
    spec_file: str
    status: str  # "passed" | "failed" | "timeout" | "error" | "no_tests"
    rules_passed: int = 0
    rules_failed: int = 0
    rules_total: int = 0
    counterexamples: List[str] = field(default_factory=list)
    stdout: str = ""
    stderr: str = ""
    elapsed_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tool": self.tool,
            "spec_file": self.spec_file,
            "status": self.status,
            "rules_passed": self.rules_passed,
            "rules_failed": self.rules_failed,
            "rules_total": self.rules_total,
            "counterexamples": self.counterexamples,
            "elapsed_seconds": round(self.elapsed_seconds, 2),
        }


class SpecRunner:
    """Runs generated formal specs against real verification tools."""

    def is_certora_available(self) -> bool:
        return shutil.which("certoraRun") is not None

    def is_halmos_available(self) -> bool:
        return shutil.which("halmos") is not None

    def is_solc_available(self) -> bool:
        return shutil.which("solc") is not None

    def is_scribble_available(self) -> bool:
        """Scribble instrumentation requires the `scribble` CLI on PATH."""
        return shutil.which("scribble") is not None

    def is_kontrol_available(self) -> bool:
        """Kontrol proving requires both the `kontrol` CLI and Foundry's `forge`."""
        return shutil.which("kontrol") is not None and shutil.which("forge") is not None

    def availability_report(self) -> Dict[str, bool]:
        return {
            "certora": self.is_certora_available(),
            "halmos": self.is_halmos_available(),
            "smtchecker": self.is_solc_available(),
            "scribble": self.is_scribble_available(),
            "kontrol": self.is_kontrol_available(),
        }

    def run_certora(
        self,
        contract_path: str,
        spec_path: str,
        contract_name: str = "MyContract",
        timeout: int = 600,
    ) -> VerificationResult:
        """Run Certora Prover on a .spec file. Requires CERTORAKEY env var."""
        if not self.is_certora_available():
            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="error",
                stderr="certoraRun not installed. See https://docs.certora.com/",
            )

        import time

        start = time.time()
        try:
            proc = subprocess.run(
                [
                    "certoraRun",
                    contract_path,
                    "--verify",
                    f"{contract_name}:{spec_path}",
                    "--json",
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            # Parse Certora output
            passed, failed = self._parse_certora_output(proc.stdout, proc.stderr)
            total = passed + failed

            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="passed" if failed == 0 and total > 0 else "failed",
                rules_passed=passed,
                rules_failed=failed,
                rules_total=total,
                stdout=proc.stdout[-2000:],  # Tail only
                stderr=proc.stderr[-1000:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="error",
                stderr=str(e),
            )

    def run_halmos(
        self,
        contract_dir: str,
        test_contract: Optional[str] = None,
        timeout: int = 300,
    ) -> VerificationResult:
        """
        Run Halmos symbolic testing on a Foundry project.

        Halmos looks for tests named `check_*` or `test*` and proves them symbolically.
        """
        if not self.is_halmos_available():
            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="error",
                stderr="halmos not installed. pip install halmos",
            )

        import time

        start = time.time()
        cmd = ["halmos"]
        if test_contract:
            cmd.extend(["--contract", test_contract])

        try:
            proc = subprocess.run(
                cmd,
                cwd=contract_dir,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            passed, failed, counterexamples = self._parse_halmos_output(proc.stdout)
            total = passed + failed

            if total == 0:
                # Halmos ran but found no tests — distinguish from actual failures
                status = "no_tests"
            elif failed == 0:
                status = "passed"
            else:
                status = "failed"

            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status=status,
                rules_passed=passed,
                rules_failed=failed,
                rules_total=total,
                counterexamples=counterexamples,
                stdout=proc.stdout[-2000:],
                stderr=proc.stderr[-500:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="error",
                stderr=str(e),
            )

    def run_smtchecker(
        self,
        contract_path: str,
        engine: str = "chc",
        timeout: int = 120,
    ) -> VerificationResult:
        """
        Run solc built-in SMTChecker.

        engine: "chc" (default, good for control-flow) or "bmc" (bounded model checking).
        """
        if not self.is_solc_available():
            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="error",
                stderr="solc not installed",
            )

        import time

        start = time.time()
        try:
            proc = subprocess.run(
                [
                    "solc",
                    "--model-checker-engine",
                    engine,
                    "--model-checker-targets",
                    "all",
                    contract_path,
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            warnings = self._parse_smtchecker_warnings(proc.stderr)

            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="passed" if len(warnings) == 0 else "failed",
                rules_failed=len(warnings),
                rules_total=len(warnings),
                counterexamples=warnings,
                stdout=proc.stdout[-1000:],
                stderr=proc.stderr[-2000:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="error",
                stderr=str(e),
            )

    def run_scribble(
        self,
        contract_path: str,
        timeout: int = 120,
    ) -> VerificationResult:
        """
        Run ConsenSys Scribble annotation instrumentation + assertion check.

        Delegates to :class:`miesc.adapters.scribble_adapter.ScribbleAdapter`,
        which arms the contract (``scribble --arm``) and reports any
        annotation/property violations. Each reported violation becomes a
        counterexample; an empty violation set means every armed assertion held.
        """
        if not self.is_scribble_available():
            return VerificationResult(
                tool="scribble",
                spec_file=contract_path,
                status="error",
                stderr="scribble not installed. npm install -g eth-scribble",
            )

        import time

        start = time.time()
        try:
            from miesc.adapters.scribble_adapter import ScribbleAdapter

            outcome = ScribbleAdapter().analyze(contract_path, timeout=timeout)
            elapsed = time.time() - start

            if outcome.get("status") == "error":
                return VerificationResult(
                    tool="scribble",
                    spec_file=contract_path,
                    status="error",
                    stderr=str(outcome.get("error", "scribble analysis failed"))[:1000],
                    elapsed_seconds=elapsed,
                )

            findings = outcome.get("findings", []) or []
            counterexamples = [
                str(f.get("message") or f.get("description") or f.get("type", "violation"))
                for f in findings
            ][:20]
            failed = len(findings)

            return VerificationResult(
                tool="scribble",
                spec_file=contract_path,
                status="passed" if failed == 0 else "failed",
                rules_passed=0,
                rules_failed=failed,
                rules_total=failed,
                counterexamples=counterexamples,
                stdout=str(outcome.get("metadata", ""))[:2000],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="scribble",
                spec_file=contract_path,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="scribble",
                spec_file=contract_path,
                status="error",
                stderr=str(e),
            )

    def run_kontrol(
        self,
        foundry_dir: str,
        match_test: Optional[str] = None,
        timeout: int = 1200,
    ) -> VerificationResult:
        """
        Run Kontrol (KEVM) symbolic invariant/property proving on a Foundry project.

        Invokes ``kontrol prove`` inside ``foundry_dir`` and parses its proof
        summary: a fully-proved run maps to ``passed``, any refuted/failed proof
        maps to ``failed`` with the reported model captured as a counterexample.
        """
        if not self.is_kontrol_available():
            return VerificationResult(
                tool="kontrol",
                spec_file=foundry_dir,
                status="error",
                stderr=(
                    "kontrol/forge not installed. "
                    "See https://docs.runtimeverification.com/kontrol"
                ),
            )

        import time

        start = time.time()
        cmd = ["kontrol", "prove"]
        if match_test:
            cmd.extend(["--match-test", match_test])

        try:
            proc = subprocess.run(
                cmd,
                cwd=foundry_dir,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            passed, failed, counterexamples = self._parse_kontrol_output(
                proc.stdout + "\n" + proc.stderr
            )
            total = passed + failed

            if total == 0:
                status = "no_tests"
            elif failed == 0:
                status = "passed"
            else:
                status = "failed"

            return VerificationResult(
                tool="kontrol",
                spec_file=foundry_dir,
                status=status,
                rules_passed=passed,
                rules_failed=failed,
                rules_total=total,
                counterexamples=counterexamples,
                stdout=proc.stdout[-2000:],
                stderr=proc.stderr[-500:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="kontrol",
                spec_file=foundry_dir,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="kontrol",
                spec_file=foundry_dir,
                status="error",
                stderr=str(e),
            )

    # ------------------------------------------------------------------
    # Parsers
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_certora_output(stdout: str, stderr: str) -> tuple[int, int]:
        """Extract pass/fail counts from Certora output."""
        # Certora prints lines like: "Rule noReentrancy: VERIFIED" or "VIOLATED"
        passed = len(re.findall(r"VERIFIED", stdout + stderr, re.IGNORECASE))
        failed = len(re.findall(r"VIOLATED|FAILED", stdout + stderr, re.IGNORECASE))
        return passed, failed

    # Strip ANSI color codes halmos emits to stdout
    _ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

    @staticmethod
    def _strip_ansi(text: str) -> str:
        return SpecRunner._ANSI_RE.sub("", text)

    @staticmethod
    def _parse_halmos_output(stdout: str) -> tuple[int, int, List[str]]:
        """Extract pass/fail + counterexamples from Halmos output."""
        clean = SpecRunner._strip_ansi(stdout)
        passed = len(re.findall(r"\[PASS\]|✓", clean))
        failed = len(re.findall(r"\[FAIL\]|✗", clean))
        counterexamples = [c.strip() for c in re.findall(r"Counterexample:\s*(.*?)(?:\n|$)", clean)]
        # Filter empties that sometimes appear from stripped ANSI residue
        counterexamples = [c for c in counterexamples if c]
        return passed, failed, counterexamples[:10]

    @staticmethod
    def _parse_kontrol_output(text: str) -> tuple[int, int, List[str]]:
        """Extract proved/failed counts + counterexamples from Kontrol output.

        Kontrol prints uppercase proof-result labels (``PASSED``/``PROVED`` vs
        ``FAILED``/``REFUTED``) in its proof summary; models/counterexamples are
        emitted under ``Counterexample:`` or ``Model:`` headers.
        """
        clean = SpecRunner._strip_ansi(text)
        passed = len(re.findall(r"\b(?:PROVED|PASSED)\b", clean))
        failed = len(re.findall(r"\b(?:FAILED|REFUTED)\b", clean))
        counterexamples = [
            c.strip()
            for c in re.findall(r"(?:Counterexample|Model)[:\s]+(.*?)(?:\n|$)", clean)
            if c.strip()
        ]
        return passed, failed, counterexamples[:10]

    @staticmethod
    def _parse_smtchecker_warnings(stderr: str) -> List[str]:
        """Extract SMTChecker warnings (each is a potential violation)."""
        warnings = []
        for m in re.finditer(r"Warning:.*?(?=\n(?:Warning:|$))", stderr, re.DOTALL):
            text = m.group(0).strip().replace("\n", " ")[:300]
            warnings.append(text)
        return warnings[:20]


def run_all_available(
    contract_path: str,
    spec_path: Optional[str] = None,
    contract_name: str = "MyContract",
) -> Dict[str, VerificationResult]:
    """Run whichever verifiers are installed and report all results."""
    runner = SpecRunner()
    availability = runner.availability_report()
    results = {}

    if availability["smtchecker"]:
        logger.info("Running SMTChecker...")
        results["smtchecker"] = runner.run_smtchecker(contract_path)

    if availability["certora"] and spec_path:
        logger.info("Running Certora Prover...")
        results["certora"] = runner.run_certora(
            contract_path, spec_path, contract_name=contract_name
        )

    if availability["halmos"]:
        contract_dir = str(Path(contract_path).parent)
        logger.info("Running Halmos...")
        results["halmos"] = runner.run_halmos(contract_dir)

    if availability.get("scribble"):
        logger.info("Running Scribble...")
        results["scribble"] = runner.run_scribble(contract_path)

    if availability.get("kontrol"):
        contract_dir = str(Path(contract_path).parent)
        logger.info("Running Kontrol...")
        results["kontrol"] = runner.run_kontrol(contract_dir)

    return results
