"""
Formal Verification Runner
===========================

Executes the specs generated by `spec_generator.py` against real verifiers:
  - Certora Prover (via certoraRun CLI)
  - Halmos (symbolic testing in Foundry)
  - SMTChecker (via solc --model-checker-engine)

This closes the loop: MIESC finds → generates spec → actually runs the proof.

Author: Fernando Boiero <fboiero@frvm.utn.edu.ar>
License: AGPL-3.0
"""

from __future__ import annotations

import json
import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class VerificationResult:
    """Result of running a formal verification spec."""

    tool: str                      # "certora", "halmos", "smtchecker"
    spec_file: str
    status: str                    # "passed" | "failed" | "timeout" | "error"
    rules_passed: int = 0
    rules_failed: int = 0
    rules_total: int = 0
    counterexamples: List[str] = field(default_factory=list)
    stdout: str = ""
    stderr: str = ""
    elapsed_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tool": self.tool,
            "spec_file": self.spec_file,
            "status": self.status,
            "rules_passed": self.rules_passed,
            "rules_failed": self.rules_failed,
            "rules_total": self.rules_total,
            "counterexamples": self.counterexamples,
            "elapsed_seconds": round(self.elapsed_seconds, 2),
        }


class SpecRunner:
    """Runs generated formal specs against real verification tools."""

    def is_certora_available(self) -> bool:
        return shutil.which("certoraRun") is not None

    def is_halmos_available(self) -> bool:
        return shutil.which("halmos") is not None

    def is_solc_available(self) -> bool:
        return shutil.which("solc") is not None

    def availability_report(self) -> Dict[str, bool]:
        return {
            "certora": self.is_certora_available(),
            "halmos": self.is_halmos_available(),
            "smtchecker": self.is_solc_available(),
        }

    def run_certora(
        self,
        contract_path: str,
        spec_path: str,
        contract_name: str = "MyContract",
        timeout: int = 600,
    ) -> VerificationResult:
        """Run Certora Prover on a .spec file. Requires CERTORAKEY env var."""
        if not self.is_certora_available():
            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="error",
                stderr="certoraRun not installed. See https://docs.certora.com/",
            )

        import time
        start = time.time()
        try:
            proc = subprocess.run(
                [
                    "certoraRun",
                    contract_path,
                    "--verify",
                    f"{contract_name}:{spec_path}",
                    "--json",
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            # Parse Certora output
            passed, failed = self._parse_certora_output(proc.stdout, proc.stderr)
            total = passed + failed

            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="passed" if failed == 0 and total > 0 else "failed",
                rules_passed=passed,
                rules_failed=failed,
                rules_total=total,
                stdout=proc.stdout[-2000:],  # Tail only
                stderr=proc.stderr[-1000:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="certora",
                spec_file=spec_path,
                status="error",
                stderr=str(e),
            )

    def run_halmos(
        self,
        contract_dir: str,
        test_contract: Optional[str] = None,
        timeout: int = 300,
    ) -> VerificationResult:
        """
        Run Halmos symbolic testing on a Foundry project.

        Halmos looks for tests named `check_*` or `test*` and proves them symbolically.
        """
        if not self.is_halmos_available():
            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="error",
                stderr="halmos not installed. pip install halmos",
            )

        import time
        start = time.time()
        cmd = ["halmos"]
        if test_contract:
            cmd.extend(["--contract", test_contract])

        try:
            proc = subprocess.run(
                cmd,
                cwd=contract_dir,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            passed, failed, counterexamples = self._parse_halmos_output(proc.stdout)

            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="passed" if failed == 0 and (passed + failed) > 0 else "failed",
                rules_passed=passed,
                rules_failed=failed,
                rules_total=passed + failed,
                counterexamples=counterexamples,
                stdout=proc.stdout[-2000:],
                stderr=proc.stderr[-500:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="halmos",
                spec_file=contract_dir,
                status="error",
                stderr=str(e),
            )

    def run_smtchecker(
        self,
        contract_path: str,
        engine: str = "chc",
        timeout: int = 120,
    ) -> VerificationResult:
        """
        Run solc built-in SMTChecker.

        engine: "chc" (default, good for control-flow) or "bmc" (bounded model checking).
        """
        if not self.is_solc_available():
            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="error",
                stderr="solc not installed",
            )

        import time
        start = time.time()
        try:
            proc = subprocess.run(
                [
                    "solc",
                    "--model-checker-engine",
                    engine,
                    "--model-checker-targets",
                    "all",
                    contract_path,
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.time() - start

            warnings = self._parse_smtchecker_warnings(proc.stderr)

            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="passed" if len(warnings) == 0 else "failed",
                rules_failed=len(warnings),
                rules_total=len(warnings),
                counterexamples=warnings,
                stdout=proc.stdout[-1000:],
                stderr=proc.stderr[-2000:],
                elapsed_seconds=elapsed,
            )
        except subprocess.TimeoutExpired:
            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="timeout",
                elapsed_seconds=timeout,
            )
        except Exception as e:
            return VerificationResult(
                tool="smtchecker",
                spec_file=contract_path,
                status="error",
                stderr=str(e),
            )

    # ------------------------------------------------------------------
    # Parsers
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_certora_output(stdout: str, stderr: str) -> tuple[int, int]:
        """Extract pass/fail counts from Certora output."""
        # Certora prints lines like: "Rule noReentrancy: VERIFIED" or "VIOLATED"
        passed = len(re.findall(r"VERIFIED", stdout + stderr, re.IGNORECASE))
        failed = len(re.findall(r"VIOLATED|FAILED", stdout + stderr, re.IGNORECASE))
        return passed, failed

    @staticmethod
    def _parse_halmos_output(stdout: str) -> tuple[int, int, List[str]]:
        """Extract pass/fail + counterexamples from Halmos output."""
        passed = len(re.findall(r"\[PASS\]|✓", stdout))
        failed = len(re.findall(r"\[FAIL\]|✗", stdout))
        counterexamples = re.findall(r"Counterexample:\s*(.*?)(?:\n|$)", stdout)
        return passed, failed, counterexamples[:10]

    @staticmethod
    def _parse_smtchecker_warnings(stderr: str) -> List[str]:
        """Extract SMTChecker warnings (each is a potential violation)."""
        warnings = []
        for m in re.finditer(r"Warning:.*?(?=\n(?:Warning:|$))", stderr, re.DOTALL):
            text = m.group(0).strip().replace("\n", " ")[:300]
            warnings.append(text)
        return warnings[:20]


def run_all_available(
    contract_path: str,
    spec_path: Optional[str] = None,
    contract_name: str = "MyContract",
) -> Dict[str, VerificationResult]:
    """Run whichever verifiers are installed and report all results."""
    runner = SpecRunner()
    availability = runner.availability_report()
    results = {}

    if availability["smtchecker"]:
        logger.info("Running SMTChecker...")
        results["smtchecker"] = runner.run_smtchecker(contract_path)

    if availability["certora"] and spec_path:
        logger.info("Running Certora Prover...")
        results["certora"] = runner.run_certora(
            contract_path, spec_path, contract_name=contract_name
        )

    if availability["halmos"]:
        contract_dir = str(Path(contract_path).parent)
        logger.info("Running Halmos...")
        results["halmos"] = runner.run_halmos(contract_dir)

    return results
