apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: miesc-hpa
  namespace: miesc
  labels:
    app: miesc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: miesc-analyzer

  minReplicas: 2
  maxReplicas: 10

  # Scale based on CPU and memory
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

  # Scaling behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down max 50% of current pods
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
      - type: Percent
        value: 100  # Scale up max 100% (double) current pods
        periodSeconds: 30
      - type: Pods
        value: 2  # Or add max 2 pods
        periodSeconds: 30
      selectPolicy: Max  # Use the policy that scales fastest
