name: Bug Report
description: Report a bug in MIESC
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below to help us investigate.

  - type: input
    id: version
    attributes:
      label: MIESC Version
      description: Output of `miesc --version` or the Docker image tag
      placeholder: "e.g., 4.2.2"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install MIESC?
      options:
        - Docker (recommended)
        - pip install
        - From source
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command `miesc analyze ...`
        2. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Output
      description: Paste relevant logs or error messages
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide:
        - OS (e.g., Ubuntu 22.04, macOS 14.0)
        - Python version
        - Solidity compiler version (if relevant)
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.0
        - solc: 0.8.20

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version
          required: true
