"""
LLM Integration Module - MIESC v4.1.0
=====================================

Sovereign LLM integration using multiple backends (Ollama, OpenAI, Anthropic, DeepSeek)
for intelligent post-processing of security analysis results across all layers.

Author: Fernando Boiero <fboiero@frvm.utn.edu.ar>
Date: December 2025
Version: 2.0.0
"""

# v4.3.0+ New LLM Components (2025-2026 Improvements)
from .agentic_contracts import (
    AbiPackedHashCollisionHardeningAgent,
    AbiPackedHashCollisionHardeningPlan,
    AbiPackedHashRisk,
    AbiPackedHashSurface,
    AdversarialOrderingPlan,
    AdversarialTransactionOrderingAgent,
    AgentCapability,
    AssetFlow,
    CapitalRequirement,
    CounterexampleEvidence,
    Create2DeploymentHardeningAgent,
    Create2DeploymentHardeningPlan,
    Create2DeploymentRisk,
    Create2DeploymentSurface,
    CrossChainMessageFlow,
    CrossChainMessageHardeningAgent,
    CrossChainMessageHardeningPlan,
    CrossChainMessageRisk,
    DelegatecallAliasRisk,
    DelegatecallStorageAliasingAgent,
    DelegatecallStorageAliasingPlan,
    DelegatecallSurface,
    DifferentialTestPlan,
    DPGAgentConfig,
    EconomicAttackPlan,
    EconomicAttackSimulationAgent,
    ERC4626VaultInflationHardeningAgent,
    ERC4626VaultInflationHardeningPlan,
    FuzzingWaypoint,
    InvariantCandidate,
    InvariantCategory,
    InvariantExtractionAgent,
    MetamorphicDiffTestingAgent,
    MetamorphicRelation,
    OracleFeedHardeningAgent,
    OracleFeedHardeningPlan,
    OracleFeedRisk,
    OracleFeedSource,
    OrderingRisk,
    OrderingTransaction,
    RandomnessEntropyHardeningAgent,
    RandomnessEntropyHardeningPlan,
    RandomnessRisk,
    RandomnessSource,
    ReasoningProvider,
    ReasoningResult,
    ReasoningTask,
    SemanticGraphEdge,
    SemanticGraphGate,
    SemanticGraphGateAgent,
    SemanticGraphNode,
    SequenceOracleAgent,
    SequenceOraclePlan,
    SequenceStep,
    SignatureDomainHardeningAgent,
    SignatureDomainHardeningPlan,
    SignatureDomainRisk,
    SignedAction,
    SnapshotFuzzingAgent,
    SnapshotFuzzingPlan,
    SnapshotSeed,
    StorageAliasPath,
    StorageLayoutChange,
    TokenHookReentrancyHardeningAgent,
    TokenHookReentrancyHardeningPlan,
    TokenHookReentrancyRisk,
    TokenHookSurface,
    UpgradeEvolutionAnalysisAgent,
    UpgradeEvolutionPlan,
    UpgradeRisk,
    VaultInflationRisk,
    VaultShareSurface,
    parse_abi_packed_hash_collision_hardening_plans,
    parse_adversarial_transaction_ordering_plans,
    parse_create2_deployment_hardening_plans,
    parse_cross_chain_message_hardening_plans,
    parse_delegatecall_storage_aliasing_plans,
    parse_differential_test_plans,
    parse_economic_attack_plans,
    parse_erc4626_vault_inflation_hardening_plans,
    parse_invariant_candidates,
    parse_oracle_feed_hardening_plans,
    parse_randomness_entropy_hardening_plans,
    parse_semantic_graph_gates,
    parse_sequence_oracle_plans,
    parse_signature_domain_hardening_plans,
    parse_snapshot_fuzzing_plans,
    parse_token_hook_reentrancy_hardening_plans,
    parse_upgrade_evolution_plans,
)
from .ensemble_detector import (
    EnsembleFinding,
    EnsembleResult,
    LLMEnsembleDetector,
    VotingStrategy,
    detect_with_ensemble,
)
from .finding_validator import (
    LLMFindingValidator,
    LLMValidation,
    ValidationResult,
    ValidatorConfig,
    validate_findings_sync,
)
from .llm_orchestrator import (
    AnthropicBackend,
    DeepSeekBackend,
    LLMBackend,
    LLMConfig,
    LLMOrchestrator,
    LLMProvider,
    LLMResponse,
    OllamaBackend,
    OpenAIBackend,
    VulnerabilityAnalysis,
    analyze_solidity,
)
from .openllama_helper import (
    OpenLLaMAHelper,
    enhance_findings_with_llm,
    explain_technical_output,
    generate_remediation_advice,
    prioritize_findings,
)
from .reasoning_provider_adapter import (
    LLMOrchestratorReasoningProvider,
    LocalHeuristicReasoningProvider,
    ReasoningProviderRoute,
    auto_reasoning_provider,
)
from .remediation_generator import (
    REMEDIATION_PATTERNS,
    Remediation,
    RemediationGenerator,
    RemediationResult,
    generate_fix,
    get_quick_fix,
)
from .vulnerability_rag import (
    EXPLOIT_EXAMPLES,
    SWC_REGISTRY,
    EnhancedFinding,
    SimilarVuln,
    VulnerabilityExample,
    VulnerabilityRAG,
)

# v5.1.0+ Embedding RAG with ChromaDB (optional dependencies)
try:
    from .embedding_rag import (
        VULNERABILITY_KNOWLEDGE_BASE,
        EmbeddingRAG,
        HybridRAG,
        RetrievalResult,
        VulnerabilityDocument,
        get_context_for_finding,
        get_rag,
        search_vulnerabilities,
    )

    _EMBEDDING_RAG_AVAILABLE = True
except ImportError:
    # ChromaDB/sentence-transformers not installed
    _EMBEDDING_RAG_AVAILABLE = False
    EmbeddingRAG = None  # type: ignore[assignment,misc]
    HybridRAG = None  # type: ignore[assignment,misc]
    RetrievalResult = None  # type: ignore[assignment,misc]
    VulnerabilityDocument = None  # type: ignore[assignment,misc]
    VULNERABILITY_KNOWLEDGE_BASE = None  # type: ignore[assignment,misc]
    get_rag = None  # type: ignore[assignment,misc]
    search_vulnerabilities = None  # type: ignore[assignment,misc]
    get_context_for_finding = None  # type: ignore[assignment,misc]

__all__ = [
    # Provider-agnostic agent contracts
    "AbiPackedHashCollisionHardeningAgent",
    "AbiPackedHashCollisionHardeningPlan",
    "AbiPackedHashRisk",
    "AbiPackedHashSurface",
    "AgentCapability",
    "AdversarialOrderingPlan",
    "AdversarialTransactionOrderingAgent",
    "AssetFlow",
    "CapitalRequirement",
    "CounterexampleEvidence",
    "Create2DeploymentHardeningAgent",
    "Create2DeploymentHardeningPlan",
    "Create2DeploymentRisk",
    "Create2DeploymentSurface",
    "CrossChainMessageFlow",
    "CrossChainMessageHardeningAgent",
    "CrossChainMessageHardeningPlan",
    "CrossChainMessageRisk",
    "DelegatecallAliasRisk",
    "DelegatecallStorageAliasingAgent",
    "DelegatecallStorageAliasingPlan",
    "DelegatecallSurface",
    "DPGAgentConfig",
    "DifferentialTestPlan",
    "EconomicAttackPlan",
    "EconomicAttackSimulationAgent",
    "ERC4626VaultInflationHardeningAgent",
    "ERC4626VaultInflationHardeningPlan",
    "InvariantCandidate",
    "InvariantCategory",
    "InvariantExtractionAgent",
    "MetamorphicDiffTestingAgent",
    "MetamorphicRelation",
    "OracleFeedHardeningAgent",
    "OracleFeedHardeningPlan",
    "OracleFeedRisk",
    "OracleFeedSource",
    "OrderingRisk",
    "OrderingTransaction",
    "RandomnessEntropyHardeningAgent",
    "RandomnessEntropyHardeningPlan",
    "RandomnessRisk",
    "RandomnessSource",
    "ReasoningProvider",
    "ReasoningResult",
    "ReasoningTask",
    "SemanticGraphEdge",
    "SemanticGraphGate",
    "SemanticGraphGateAgent",
    "SemanticGraphNode",
    "SignatureDomainHardeningAgent",
    "SignatureDomainHardeningPlan",
    "SignatureDomainRisk",
    "SignedAction",
    "FuzzingWaypoint",
    "SnapshotFuzzingAgent",
    "SnapshotFuzzingPlan",
    "SnapshotSeed",
    "StorageAliasPath",
    "StorageLayoutChange",
    "TokenHookReentrancyHardeningAgent",
    "TokenHookReentrancyHardeningPlan",
    "TokenHookReentrancyRisk",
    "TokenHookSurface",
    "UpgradeEvolutionAnalysisAgent",
    "UpgradeEvolutionPlan",
    "UpgradeRisk",
    "VaultInflationRisk",
    "VaultShareSurface",
    "SequenceOracleAgent",
    "SequenceOraclePlan",
    "SequenceStep",
    "parse_abi_packed_hash_collision_hardening_plans",
    "parse_invariant_candidates",
    "parse_oracle_feed_hardening_plans",
    "parse_adversarial_transaction_ordering_plans",
    "parse_create2_deployment_hardening_plans",
    "parse_cross_chain_message_hardening_plans",
    "parse_delegatecall_storage_aliasing_plans",
    "parse_differential_test_plans",
    "parse_erc4626_vault_inflation_hardening_plans",
    "parse_randomness_entropy_hardening_plans",
    "parse_semantic_graph_gates",
    "parse_signature_domain_hardening_plans",
    "parse_snapshot_fuzzing_plans",
    "parse_sequence_oracle_plans",
    "parse_token_hook_reentrancy_hardening_plans",
    "parse_upgrade_evolution_plans",
    "LLMOrchestratorReasoningProvider",
    "LocalHeuristicReasoningProvider",
    "ReasoningProviderRoute",
    "auto_reasoning_provider",
    "parse_economic_attack_plans",
    # Legacy OpenLLaMA helpers
    "OpenLLaMAHelper",
    "enhance_findings_with_llm",
    "explain_technical_output",
    "prioritize_findings",
    "generate_remediation_advice",
    # New LLM Orchestrator
    "LLMProvider",
    "LLMConfig",
    "LLMResponse",
    "VulnerabilityAnalysis",
    "LLMBackend",
    "OllamaBackend",
    "OpenAIBackend",
    "AnthropicBackend",
    "DeepSeekBackend",
    "LLMOrchestrator",
    "analyze_solidity",
    # LLM Finding Validator
    "LLMFindingValidator",
    "LLMValidation",
    "ValidationResult",
    "ValidatorConfig",
    "validate_findings_sync",
    # v4.3.0+ LLM Ensemble Detector
    "LLMEnsembleDetector",
    "EnsembleFinding",
    "EnsembleResult",
    "VotingStrategy",
    "detect_with_ensemble",
    # v4.3.0+ Vulnerability RAG (keyword-based)
    "VulnerabilityRAG",
    "VulnerabilityExample",
    "SimilarVuln",
    "EnhancedFinding",
    "SWC_REGISTRY",
    "EXPLOIT_EXAMPLES",
    # v4.3.0+ Remediation Generator
    "RemediationGenerator",
    "Remediation",
    "RemediationResult",
    "REMEDIATION_PATTERNS",
    "generate_fix",
    "get_quick_fix",
    # v5.1.0+ Embedding RAG with ChromaDB (optional)
    "EmbeddingRAG",
    "HybridRAG",
    "RetrievalResult",
    "VulnerabilityDocument",
    "VULNERABILITY_KNOWLEDGE_BASE",
    "get_rag",
    "search_vulnerabilities",
    "get_context_for_finding",
    "_EMBEDDING_RAG_AVAILABLE",
]
