# MIESC MCP Server Configuration
# Model Context Protocol - Server Configuration

agent:
  id: "miesc-agent-v3.0.0"
  name: "MIESC"
  protocol_version: "mcp/1.0"

server:
  host: "0.0.0.0"
  port: 8080
  workers: 4
  timeout: 300

  endpoints:
    jsonrpc: "/mcp/jsonrpc"
    websocket: "/mcp/ws"
    rest: "/api/v1"
    health: "/health"
    metrics: "/metrics"

security:
  enable_auth: false  # Set to true for production
  api_key_header: "X-MIESC-API-Key"
  rate_limit:
    enabled: true
    requests_per_minute: 60
  cors:
    enabled: true
    origins: ["*"]

miesc_config:
  # Tool configuration
  tools:
    slither:
      enabled: true
      timeout: 120
      exclude_informational: true
    mythril:
      enabled: true
      timeout: 180
      execution_timeout: 300
    aderyn:
      enabled: true
      timeout: 60
    echidna:
      enabled: false  # Requires additional setup
      timeout: 600
    solhint:
      enabled: true
      timeout: 30

  # AI correlation
  ai_correlation:
    enabled: true
    model: "gpt-4o"
    temperature: 0.2
    max_tokens: 1500
    fallback_to_heuristics: true

  # Policy mapping
  policy_mapping:
    enabled: true
    standards:
      - "ISO/IEC 27001:2022"
      - "NIST CSF"
      - "OWASP SC Top 10"
      - "CWE"
      - "SWC"
      - "MITRE ATT&CK"

  # Risk assessment
  risk_assessment:
    enabled: true
    business_context:
      default_value_locked: 0
      default_user_count: 0
      default_is_production: false

  # Reporting
  reporting:
    formats: ["json", "html", "pdf"]
    output_directory: "analysis/results"
    include_raw_findings: true
    include_audit_trail: true

logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/miesc_server.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

context_bus:
  enabled: true
  max_history: 1000
  export_audit_trail: true
  audit_trail_path: "analysis/audit_trails"

performance:
  enable_caching: true
  cache_ttl: 3600  # seconds
  parallel_execution: true
  max_parallel_tools: 3

experimental:
  enable_soroban_support: false  # Future feature (v3.5)
  enable_cross_chain: false
  enable_ml_models: false
