"""
MIESC CLI - Init Commands

Commands for initializing MIESC integrations for build frameworks.

Author: Fernando Boiero
License: AGPL-3.0
"""

import sys
from pathlib import Path

import click

from miesc.cli.utils import error, info, print_banner, success, warning


@click.group()
def init():
    """Initialize MIESC integrations for build frameworks."""
    pass


@init.command("foundry")
@click.option("--profile", default="default", help="Foundry profile to configure")
@click.option("--fail-on", default="high", type=click.Choice(["critical", "high", "medium", "low"]))
@click.option(
    "--hook-script", is_flag=True, help="Create full hook script instead of inline command"
)
def init_foundry(profile, fail_on, hook_script):
    """Initialize MIESC integration for Foundry projects.

    Adds post-build hook to foundry.toml and optionally creates a hook script.

    Examples:
        miesc init foundry                    # Add to default profile
        miesc init foundry --profile ci       # Add to CI profile
        miesc init foundry --hook-script      # Create full hook script
        miesc init foundry --fail-on critical # Only fail on critical
    """
    print_banner()

    foundry_toml = Path("foundry.toml")

    if not foundry_toml.exists():
        error("foundry.toml not found in current directory")
        info("Run this command from your Foundry project root")
        sys.exit(1)

    info("Configuring MIESC for Foundry project...")

    # Read current config
    content = foundry_toml.read_text()

    # Check if already configured
    if "miesc" in content.lower():
        warning("MIESC appears to already be configured in foundry.toml")
        if not click.confirm("Overwrite existing configuration?"):
            return

    if hook_script:
        # Create hook script
        scripts_dir = Path("scripts")
        scripts_dir.mkdir(exist_ok=True)

        hook_path = scripts_dir / "miesc-hook.sh"
        hook_content = f"""#!/bin/bash
# =============================================================================
# MIESC Foundry Post-Build Hook
# Generated by: miesc init foundry --hook-script
# =============================================================================

set -e

# Configuration
FAIL_ON="${{MIESC_FAIL_ON:-{fail_on}}}"
CONTRACTS="${{MIESC_CONTRACTS:-./src}}"
REPORT_FILE="miesc-report.json"

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[0;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

log_info() {{ echo -e "${{BLUE}}[MIESC]${{NC}} $1"; }}
log_success() {{ echo -e "${{GREEN}}[MIESC]${{NC}} $1"; }}
log_error() {{ echo -e "${{RED}}[MIESC]${{NC}} $1"; }}

# Check MIESC
if ! command -v miesc &> /dev/null; then
    log_error "MIESC not found. Install: pip install miesc"
    exit 1
fi

# Find contracts
if [ ! -d "$CONTRACTS" ]; then
    CONTRACTS="./contracts"
fi

SOL_COUNT=$(find "$CONTRACTS" -name "*.sol" -type f 2>/dev/null | wc -l | tr -d ' ')
if [ "$SOL_COUNT" -eq 0 ]; then
    log_info "No Solidity files found"
    exit 0
fi

log_info "Scanning $SOL_COUNT contracts..."

# Run audit
miesc audit quick "$CONTRACTS" --ci --output json > "$REPORT_FILE" 2>&1 || true

# Parse results
if command -v jq &> /dev/null && [ -f "$REPORT_FILE" ]; then
    CRITICAL=$(jq -r '.summary.critical // 0' "$REPORT_FILE")
    HIGH=$(jq -r '.summary.high // 0' "$REPORT_FILE")
    MEDIUM=$(jq -r '.summary.medium // 0' "$REPORT_FILE")
    LOW=$(jq -r '.summary.low // 0' "$REPORT_FILE")

    echo ""
    log_info "=== Audit Summary ==="
    echo -e "  ${{RED}}Critical:${{NC}} $CRITICAL"
    echo -e "  ${{YELLOW}}High:${{NC}}     $HIGH"
    echo -e "  ${{YELLOW}}Medium:${{NC}}   $MEDIUM"
    echo -e "  ${{BLUE}}Low:${{NC}}      $LOW"

    # Check threshold
    SHOULD_FAIL=false
    case "$FAIL_ON" in
        critical) [ "$CRITICAL" -gt 0 ] && SHOULD_FAIL=true ;;
        high) [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ] && SHOULD_FAIL=true ;;
        medium) [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ] || [ "$MEDIUM" -gt 0 ] && SHOULD_FAIL=true ;;
        low) [ "$((CRITICAL + HIGH + MEDIUM + LOW))" -gt 0 ] && SHOULD_FAIL=true ;;
    esac

    if [ "$SHOULD_FAIL" = true ]; then
        log_error "Issues found above threshold ($FAIL_ON)"
        exit 1
    fi

    log_success "Audit passed (threshold: $FAIL_ON)"
fi
"""
        hook_path.write_text(hook_content)
        hook_path.chmod(0o755)
        success(f"Created {hook_path}")

        post_build_cmd = "./scripts/miesc-hook.sh"
    else:
        post_build_cmd = f"miesc audit quick ./src --ci --fail-on {fail_on}"

    # Update foundry.toml
    profile_section = f"[profile.{profile}]"

    if profile_section in content:
        # Add to existing profile
        lines = content.split("\n")
        new_lines = []
        in_target_profile = False
        added = False

        for line in lines:
            new_lines.append(line)

            if line.strip() == profile_section:
                in_target_profile = True
            elif line.strip().startswith("[") and in_target_profile:
                # End of target profile, insert before next section
                if not added:
                    new_lines.insert(-1, f'post_build_hook = "{post_build_cmd}"')
                    new_lines.insert(-1, "")
                    added = True
                in_target_profile = False

        # If we're still in target profile at end of file
        if in_target_profile and not added:
            new_lines.append(f'post_build_hook = "{post_build_cmd}"')

        content = "\n".join(new_lines)
    else:
        # Add new profile section
        content += f"""

{profile_section}
post_build_hook = "{post_build_cmd}"
"""

    foundry_toml.write_text(content)
    success("Updated foundry.toml with MIESC post-build hook")

    # Summary
    print("")  # noqa: T201
    info("Configuration complete!")
    print(f"  Profile: {profile}")  # noqa: T201
    print(f"  Fail on: {fail_on}")  # noqa: T201
    print(f"  Hook: {post_build_cmd}")  # noqa: T201
    print("")  # noqa: T201
    info("Usage:")
    print("  forge build                  # Triggers MIESC audit")  # noqa: T201
    print(f"  forge build --profile {profile}  # Uses configured profile")  # noqa: T201


@init.command("hardhat")
@click.option("--fail-on", default="high", type=click.Choice(["critical", "high", "medium", "low"]))
def init_hardhat(fail_on):
    """Initialize MIESC integration for Hardhat projects.

    Creates hardhat.config.js plugin configuration.

    Examples:
        miesc init hardhat
        miesc init hardhat --fail-on critical
    """
    print_banner()

    # Check for hardhat config
    config_files = ["hardhat.config.js", "hardhat.config.ts"]
    config_file = None
    for f in config_files:
        if Path(f).exists():
            config_file = Path(f)
            break

    if not config_file:
        error("hardhat.config.js/ts not found in current directory")
        info("Run this command from your Hardhat project root")
        sys.exit(1)

    info("Configuring MIESC for Hardhat project...")

    # Create miesc task file
    tasks_dir = Path("tasks")
    tasks_dir.mkdir(exist_ok=True)

    task_file = tasks_dir / "miesc.js"
    task_content = f"""// MIESC Security Audit Task for Hardhat
// Generated by: miesc init hardhat

const {{ task }} = require("hardhat/config");
const {{ exec }} = require("child_process");
const {{ promisify }} = require("util");
const execAsync = promisify(exec);

task("miesc", "Run MIESC security audit")
  .addOptionalParam("level", "Audit level: quick or full", "quick")
  .addOptionalParam("failOn", "Fail on severity: critical, high, medium, low", "{fail_on}")
  .addFlag("ci", "CI mode - exit with error code on issues")
  .setAction(async (taskArgs, hre) => {{
    const {{ level, failOn, ci }} = taskArgs;

    console.log("\\n[MIESC] Running security audit...\\n");

    const contractsDir = hre.config.paths.sources;
    let cmd = `miesc audit ${{level}} ${{contractsDir}}`;

    if (ci) {{
      cmd += ` --ci --fail-on ${{failOn}}`;
    }}

    try {{
      const {{ stdout, stderr }} = await execAsync(cmd);
      console.log(stdout);
      if (stderr) console.error(stderr);
    }} catch (error) {{
      console.error(error.stdout || error.message);
      if (ci) {{
        process.exit(1);
      }}
    }}
  }});

task("miesc:quick", "Run quick MIESC audit")
  .setAction(async (_, hre) => {{
    await hre.run("miesc", {{ level: "quick" }});
  }});

task("miesc:full", "Run full MIESC audit")
  .setAction(async (_, hre) => {{
    await hre.run("miesc", {{ level: "full" }});
  }});

// Hook into compile task
task("compile")
  .setAction(async (args, hre, runSuper) => {{
    await runSuper(args);

    if (process.env.MIESC_ON_COMPILE === "true") {{
      console.log("\\n[MIESC] Post-compile security check...\\n");
      await hre.run("miesc", {{ level: "quick" }});
    }}
  }});

module.exports = {{}};
"""
    task_file.write_text(task_content)
    success(f"Created {task_file}")

    # Show instructions
    print("")  # noqa: T201
    info("Add to your hardhat.config.js:")
    print('  require("./tasks/miesc");')  # noqa: T201
    print("")  # noqa: T201
    info("Usage:")
    print("  npx hardhat miesc              # Quick audit")  # noqa: T201
    print("  npx hardhat miesc --level full # Full audit")  # noqa: T201
    print("  npx hardhat miesc --ci         # CI mode with exit code")  # noqa: T201
    print("")  # noqa: T201
    info("Enable audit on compile:")
    print("  MIESC_ON_COMPILE=true npx hardhat compile")  # noqa: T201


@init.command("github")
@click.option("--workflow-name", default="security", help="Workflow file name")
def init_github(workflow_name):
    """Initialize GitHub Actions workflow for MIESC.

    Creates .github/workflows/security.yml

    Examples:
        miesc init github
        miesc init github --workflow-name audit
    """
    print_banner()

    workflows_dir = Path(".github/workflows")
    workflows_dir.mkdir(parents=True, exist_ok=True)

    workflow_file = workflows_dir / f"{workflow_name}.yml"

    workflow_content = """# MIESC Security Audit Workflow
# Generated by: miesc init github

name: Security Audit

on:
  push:
    branches: [main, master, develop]
    paths:
      - '**.sol'
  pull_request:
    paths:
      - '**.sol'
  workflow_dispatch:

jobs:
  miesc-audit:
    name: MIESC Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MIESC
        run: |
          pip install miesc
          miesc --version

      - name: Run Security Audit
        run: |
          miesc audit quick . --ci --output sarif > miesc.sarif || true
          miesc audit quick . --output json > miesc.json || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: miesc.sarif
        continue-on-error: true

      - name: Generate Summary
        if: always()
        run: |
          echo "## MIESC Security Audit" >> $GITHUB_STEP_SUMMARY
          if [ -f miesc.json ]; then
            echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
            echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
            echo "| Critical | $(jq -r '.summary.critical // 0' miesc.json) |" >> $GITHUB_STEP_SUMMARY
            echo "| High | $(jq -r '.summary.high // 0' miesc.json) |" >> $GITHUB_STEP_SUMMARY
            echo "| Medium | $(jq -r '.summary.medium // 0' miesc.json) |" >> $GITHUB_STEP_SUMMARY
            echo "| Low | $(jq -r '.summary.low // 0' miesc.json) |" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: miesc-results
          path: |
            miesc.json
            miesc.sarif
"""

    workflow_file.write_text(workflow_content)
    success(f"Created {workflow_file}")

    print("")  # noqa: T201
    info("GitHub Actions workflow created!")
    print(f"  File: {workflow_file}")  # noqa: T201
    print("")  # noqa: T201
    info("The workflow will:")
    print("  - Run on push/PR to main, master, develop")  # noqa: T201
    print("  - Upload results to GitHub Code Scanning")  # noqa: T201
    print("  - Generate summary in workflow run")  # noqa: T201
