name: Echidna Fuzzing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Run nightly

jobs:
  echidna:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Echidna
        uses: crytic/echidna-action@v2
        with:
          echidna-version: v2.2.1

      - name: Install solc
        run: |
          pip install solc-select
          solc-select install 0.8.20
          solc-select use 0.8.20

      - name: Run Echidna Fuzzing
        run: |
          mkdir -p analysis/echidna/results

          # Fuzz each vulnerable contract
          for contract in src/contracts/vulnerable/**/*.sol; do
            echo "Fuzzing $contract..."
            echidna $contract \
              --config analysis/echidna/config.yaml \
              --format text \
              --timeout 300 \
              > "analysis/echidna/results/$(basename $contract .sol).txt" || true
          done

      - name: Upload Echidna Results
        uses: actions/upload-artifact@v4
        with:
          name: echidna-results
          path: analysis/echidna/results/

      - name: Check for property violations
        run: |
          if grep -r "failed!" analysis/echidna/results/; then
            echo "::warning::Echidna found property violations"
          fi
